CREATE DATABASE IF NOT EXISTS monitoring
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE monitoring;

CREATE TABLE IF NOT EXISTS monitors (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  url VARCHAR(2048) NOT NULL,
  status ENUM('UNKNOWN', 'ONLINE', 'OFFLINE') NOT NULL DEFAULT 'UNKNOWN',
  responseTime INT NULL,
  statusCode SMALLINT NULL,
  lastError VARCHAR(255) NULL,
  lastCheckedAt DATETIME NULL,
  createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY UQ_monitors_url (url) USING HASH
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
